"""
WAF Detector - Detect Web Application Firewall
"""
import requests
import warnings

warnings.filterwarnings('ignore', message='Unverified HTTPS request')

# WAF signatures
WAF_SIGNATURES = {
    'Cloudflare': {
        'headers': ['cf-ray', 'cf-cache-status', '__cfduid'],
        'cookies': ['__cfduid', '__cflb'],
        'content': ['cloudflare', 'cf-error-details']
    },
    'AWS WAF': {
        'headers': ['x-amzn-requestid', 'x-amz-cf-id'],
        'content': ['Access Denied', 'AWS']
    },
    'Akamai': {
        'headers': ['akamai-origin-hop', 'akamai-x-cache'],
        'content': ['AkamaiGHost', 'akamai']
    },
    'Imperva (Incapsula)': {
        'headers': ['x-cdn', 'x-iinfo'],
        'cookies': ['incap_ses', 'visid_incap'],
        'content': ['incapsula', 'imperva']
    },
    'Sucuri': {
        'headers': ['x-sucuri-id', 'x-sucuri-cache'],
        'content': ['sucuri', 'cloudproxy']
    },
    'ModSecurity': {
        'headers': ['mod_security'],
        'content': ['mod_security', 'modsecurity']
    },
    'Wordfence': {
        'headers': ['wordfence'],
        'content': ['wordfence', 'generated by wordfence']
    },
    'F5 BIG-IP': {
        'headers': ['x-wa-info', 'bigipserver'],
        'cookies': ['bigipserver', 'f5_cspm'],
        'content': ['f5', 'bigip']
    },
    'Barracuda': {
        'headers': ['barra_counter_session'],
        'content': ['barracuda']
    },
    'Fortinet FortiWeb': {
        'headers': ['fortigate', 'fortiweb'],
        'content': ['fortinet', 'fortiweb']
    },
    'Citrix NetScaler': {
        'headers': ['ns_af', 'citrix_ns_id'],
        'cookies': ['ns_af', 'citrix_ns_id'],
        'content': ['netscaler']
    },
    'DenyAll': {
        'headers': ['sessioncookie'],
        'content': ['denyall']
    }
}

def detect_waf(domain):
    """
    Detect Web Application Firewall
    """
    result = {
        'domain': domain,
        'waf_detected': False,
        'waf_name': None,
        'confidence': 'Unknown',
        'indicators': []
    }
    
    try:
        url = f'https://{domain}'
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        
        # Normal request
        response = requests.get(url, headers=headers, timeout=5, verify=False, allow_redirects=True)
        
        response_headers = {k.lower(): v.lower() for k, v in response.headers.items()}
        response_cookies = {k.lower(): v.lower() for k, v in response.cookies.items()}
        response_content = response.text.lower()
        
        # Check each WAF signature
        matches = {}
        
        for waf_name, signatures in WAF_SIGNATURES.items():
            match_count = 0
            found_indicators = []
            
            # Check headers
            if 'headers' in signatures:
                for header in signatures['headers']:
                    if header.lower() in response_headers:
                        match_count += 2
                        found_indicators.append(f'Header: {header}')
            
            # Check cookies
            if 'cookies' in signatures:
                for cookie in signatures['cookies']:
                    if cookie.lower() in response_cookies:
                        match_count += 2
                        found_indicators.append(f'Cookie: {cookie}')
            
            # Check content
            if 'content' in signatures:
                for content_sig in signatures['content']:
                    if content_sig.lower() in response_content:
                        match_count += 1
                        found_indicators.append(f'Content: {content_sig}')
            
            if match_count > 0:
                matches[waf_name] = {
                    'score': match_count,
                    'indicators': found_indicators
                }
        
        # Determine WAF
        if matches:
            # Get WAF with highest score
            best_match = max(matches.items(), key=lambda x: x[1]['score'])
            waf_name, waf_data = best_match
            
            result['waf_detected'] = True
            result['waf_name'] = waf_name
            result['indicators'] = waf_data['indicators']
            
            # Determine confidence
            if waf_data['score'] >= 4:
                result['confidence'] = 'High'
            elif waf_data['score'] >= 2:
                result['confidence'] = 'Medium'
            else:
                result['confidence'] = 'Low'
            
            # List all possible WAFs
            result['possible_wafs'] = [
                {'name': name, 'score': data['score']} 
                for name, data in sorted(matches.items(), key=lambda x: x[1]['score'], reverse=True)
            ]
        
        # Additional checks with malicious payload
        try:
            malicious_url = f'{url}?id=1\' OR \'1\'=\'1'
            mal_response = requests.get(malicious_url, headers=headers, timeout=3, verify=False)
            
            if mal_response.status_code in [403, 406, 419, 429, 503]:
                if not result['waf_detected']:
                    result['waf_detected'] = True
                    result['waf_name'] = 'Generic WAF'
                    result['confidence'] = 'Medium'
                    result['indicators'].append(f'Blocked malicious request (Status: {mal_response.status_code})')
        except:
            pass
        
    except requests.Timeout:
        result['error'] = 'Request timeout'
    except requests.RequestException as e:
        result['error'] = f'Request failed: {str(e)}'
    except Exception as e:
        result['error'] = f'Detection error: {str(e)}'
    
    return result
